### ISSUE TITLE
create command doesn't use patch_directory correctly

### ISSUE THREAD

**Issue by mdeletter** [dbpatch/DbPatch#11]
cat dbpatch.ini

[dbpatch]
limit = 10
default_branch = default 
patch_directory = db/patches
patch_prefix = patch 
color = true
dump_before_update = false 
....

dbpatch create --type=php
creates db/patchespatch-0003.php (instead of db/patches/patch-0003.php)

**Comment by sndpl** [comment]
Fixed in development branch
