### ISSUE TITLE
default_branch in config does not work

### ISSUE THREAD

**Issue by melvin-ibuildings** [dbpatch/DbPatch#16]
when setting default_branche to something else then default dbpatch does not listen to this.

Example
with:
default_branch = cms

Execute:
dbpatch create --type=mysql

Result:
SUCCESS: Created empty patch ../../../../../database/cms/patch-0002.sql

Expected:
SUCCESS: Created empty patch ../../../../../database/cms/patch-cms-0001.sql

**Comment by sndpl** [comment]
Fixed
