### ISSUE TITLE
[Insight] Source code should not contain TODO comments

### ISSUE THREAD

**Issue by sndpl** [dbpatch/DbPatch#35]
**[in src/DbPatch/Command/Remove.php, line 121](https://github.com/dbpatch/DbPatch/blob/master/src/DbPatch/Command/Remove.php#L121)**

> TODO comments are left in the code when a feature (or a bug) isn't completely developed (or fixed). You should complete the implementation and remove the comment.

```
            $branchMsg = (empty($branchName) ? ""
                    : "for branch '$branchName' ");
            $this->getWriter()->line("Patch $patchNumber not found {$branchMsg} in `" . self::TABLE . "` table");
        }
        else if (count($patchRecords) > 1) {
            // @todo this is not happening anymore ???????
            $branchArray = array();
            foreach ($patchRecords as $branch) {
                $branchArray[] = $branch['branch'];
            }

```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/7e3d0bdf-e64d-42a1-9654-a218e27d6a10/analyses/2)_

**Comment by mdeletter** [comment]
Fixed
