### ISSUE TITLE
Support for non-MySQL databases?

### ISSUE THREAD

**Issue by relaxnow** [dbpatch/DbPatch#7]
In the configuration  you can specify an adapter, however SQL files are imported using the MySQL client, is it in scope for DbPatch to be able to work with multiple vendors?

**Comment by sndpl** [comment]
I just committed a patch and we now have DbPatch_Db_Adapter_\* adapters which have an import and dump function. At the moment we only have an adapter for MySQL, but contributions for other adapters are welcome :)

**Comment by sndpl** [comment]
Just wrote an Sqlite3 adapter, will be released in the next version of DbPatch. PostgreSQL is also on my Todo list :)

**Comment by sndpl** [comment]
Fixed with issue #21 which is added to the development branch.
